name: seat_reservation_app 
description: add seat status screen with periodic updates

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic.ttf
  assets:
    - assets/images/학생페이지 뒷배경.png
    - assets/images/검색 사진.png
    - assets/images/로고.png
    - assets/images/도서관이용증.png
    - assets/images/자리 이용 예약.png
    - assets/images/웃는사자.png
    - assets/images/QR.png
 